BreadBuilder/ViewModels/WeatherViewModel.cs
using BreadBuilder.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BreadBuilder.ViewModels
{
    public class WeatherViewModel
    {
        public string City { get; set; }
        public string Temp { get; set; }
        public string Humidity { get; set; }
        public int BreadID { get; set; }
        public double DewPoint { get; set; }


        public Bread Bread { get; set; }
        public IList<RecipeItem> Items { get; set; }
        public double Hydration { get; set; }
        public IList<double> TotalWeights { get; set; }

        public string AdjustedLiquid { get; set; }
        public string AdjustmentPercent { get; set; }
        public string AdjustmentMessage { get; set; }
    }
}

BreadBuilder/Controllers/BreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BreadBuilder.Data;
using BreadBuilder.Models;
using BreadBuilder.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Session;

/*
 * TODO: refactor code so that the whole conversion process for bread hydration level takes place 
 *       in the Conversions class.  Currently, it is used in several handlers--ViewBread, ConvertToGrams ect...
 *   
 * TODO: refactor code so that method calls replace the code inside of controllers... for the most part...
 */
namespace BreadBuilder.Controllers
{
    public class BreadController : Controller
    {
        private BreadDbContext context;
        
        public BreadController(BreadDbContext dbContext)
        {
            context = dbContext;
        }

    

        public IActionResult Add()
        {      
            AddBreadViewModel addBreadViewModel = new AddBreadViewModel();
            
            return View(addBreadViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddBreadViewModel addBreadViewModel)
        {
            if (ModelState.IsValid)
            {

                //converts the user id to an integer from tempdata
                //the user id is boxed in TempData when the user logs in
                int userId = Convert.ToInt32(TempData["UserId"].ToString());

                Bread newBread = DataBaseAccess.AddToDataBase(addBreadViewModel, userId, context);

                TempData["UserId"] = userId;

                TempData.Keep();

                return RedirectToAction($"/ViewBread/{newBread.ID}");
            }

            return View(addBreadViewModel);

        }  

       public IActionResult ViewBread(int id)
        {
            
            ViewBreadViewModel viewModel = DataBaseAccess.ViewBread(id, context);
            TempData.Keep();
            
            return View(viewModel);
        }

        //Controller converts all values of recipe items to grams...  Nothing is saved, everything is just converted for the view...
        public IActionResult ConvertToGrams(int id)
        {

            ViewBreadViewModel viewModel = DataBaseAccess.ConvertToGramsViewModel(id, context);

            TempData.Keep();

            return View("ViewBread", viewModel);
        }

        //Controller converts all values of recipe items to ounces...  Nothing is saved, everything is just converted for the view...
        public IActionResult ConvertToOunces(int id)
        {
            ViewBreadViewModel viewModel = DataBaseAccess.ConvertToOuncesViewModel(id, context);

            TempData.Keep();

            return View("ViewBread", viewModel);
        }

        //Controller for the initial view of the EditBread view...
        public IActionResult EditBread(int id)
        {

            EditBreadViewModel viewModel = DataBaseAccess.EditBreadView(id, context);

            TempData.Keep();

            return View(viewModel);

        }

        [HttpPost]
        public IActionResult EditBread(EditBreadViewModel editBreadViewModel)
        {
            if (ModelState.IsValid)
            {
              

                //holds the list of recipe items from viewmodel
                List<RecipeItem> items = context.RecipeItems.Include(i => i.RecipeIngredient).Include(y => y.RecipeMeasurement).Where(x => x.Bread.ID == editBreadViewModel.ID).ToList();

                Bread theBread = context.Breads.Single(b => b.ID == editBreadViewModel.ID);

                List<RecipeItem> recipeItems = editBreadViewModel.RecipeItems.ToList();

                theBread.Name = editBreadViewModel.Name;

                theBread.Instructions = editBreadViewModel.Instructions;

                theBread.BakeTemp = editBreadViewModel.BakeTemp;

                theBread.BakeTime = editBreadViewModel.BakeTime;

                theBread.FermentTime = editBreadViewModel.FermentTime;

                theBread.ProofTime = editBreadViewModel.ProofTime;

                context.Breads.Update(theBread);
                
                //updates the recipe item, ingredient, and measurement
                //currently creating new database entries for ingredient and measurement
                //needs to update database entries instead of creating new entries
                for(var i =0; i < items.Count; i++)
                {
                    items[i].RecipeIngredient.Name = recipeItems[i].RecipeIngredient.Name;
                    items[i].RecipeMeasurement.Value = recipeItems[i].RecipeMeasurement.Value;
                    items[i].RecipeMeasurement.Unit = recipeItems[i].RecipeMeasurement.Unit;

                  
                    context.RecipeItems.Update(items[i]);
                }

                context.SaveChanges();



                TempData.Keep();

                return RedirectToAction($"/ViewBread/{editBreadViewModel.ID}");
            }

            return View(editBreadViewModel);



        }

     


        public IActionResult Delete(int id)
        {
            List<RecipeItem> items = context.RecipeItems.Include(i => i.RecipeIngredient)
                .Include(y => y.RecipeMeasurement)
                .Where(x => x.Bread.ID == id)
                .ToList();

            Bread theBread = context.Breads.Single(b => b.ID == id);

            foreach(var item in items)
            {
                context.Ingredients.Remove(item.RecipeIngredient);
                context.Measurements.Remove(item.RecipeMeasurement);
                context.RecipeItems.Remove(item);
            }
            context.Breads.Remove(theBread);

            context.SaveChanges();
            return RedirectToAction("UserRecipeList", "User");
        }
    }
}

BreadBuilder/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using BreadBuilder.Data;
using BreadBuilder.Models;
using BreadBuilder.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BreadBuilder.Controllers
{
    [Produces("application/json")]
    public class WeatherController : Controller
    {

        private BreadDbContext context;

        public WeatherController(BreadDbContext dbContext)
        {
            context = dbContext;
        }


        public IActionResult Index(int id)
        {
            
            BreadWeatherViewModel viewModel = new BreadWeatherViewModel
            {
                BreadId = id
            };
            return View(viewModel);
        }
      

        [HttpGet]
        public async Task<IActionResult> City(BreadWeatherViewModel breadWeatherViewModel)
        {
            int id = breadWeatherViewModel.BreadId;
            string city = breadWeatherViewModel.City;
            Bread theBread = context.Breads.Single(b => b.ID == id);
            List<RecipeItem> items = context.RecipeItems.Include(i => i.RecipeIngredient).Include(y => y.RecipeMeasurement).Where(x => x.Bread.ID == id).ToList();

            using (var client = new HttpClient())
            {
                try
                {
                    client.BaseAddress = new Uri("http://api.openweathermap.org");
                    var response = await client.GetAsync($"/data/2.5/weather?q={city}&appid=47a5c131dcaf6e49c667eac297513dd8&units=imperial");
                    response.EnsureSuccessStatusCode();

                    var stringResult = await response.Content.ReadAsStringAsync();
                    var rawWeather = JsonConvert.DeserializeObject<OpenWeatherResponse>(stringResult);

                    double dewPoint = Conversions.DewPoint(rawWeather.Main.Temp, rawWeather.Main.Humidity);

                    double hydration = Conversions.HydrationLevel(items);

                    List<double> totalWeights = Conversions.TotalWeights(items);

                    WeatherViewModel weatherViewModel = new WeatherViewModel
                    {
                        City = rawWeather.Name,
                        Temp = rawWeather.Main.Temp,
                        Humidity = rawWeather.Main.Humidity,
                        BreadID = breadWeatherViewModel.BreadId,
                        DewPoint = dewPoint,
                        Bread = theBread,
                        Items = items,
                        Hydration = hydration,
                        TotalWeights = totalWeights

                    };

                    WeatherViewModel viewModel = Conversions.WeatherAdjustment(weatherViewModel);

                    TempData.Keep();

                    return View("ViewWeather", viewModel);




                   /* return Ok(new
                    {
                        Temp = rawWeather.Main.Temp,
                        Humidity = rawWeather.Main.Humidity,
                        Summary = string.Join(",", rawWeather.Weather.Select(x => x.Main)),
                        City = rawWeather.Name
                    }); */
                }
                catch (HttpRequestException httpRequestException)
                {
                    return BadRequest($"Error getting weather from OpenWeather: {httpRequestException.Message}");
                }
            }
        }

    }
}

BreadBuilder/Views/Weather/Index.cshtml
@model BreadBuilder.ViewModels.BreadWeatherViewModel
@{
    ViewData["Title"] = "Weather";
}
<br />
<div class="jumbotron">
    <h2>Weather Condition Adjustments</h2>
    <hr />
    <p>When the Weather is extremely humid or dry, bread recipes
       often need to be adjusted to compensate for the abundance
       or lack of moisture.  Search the city you are in and your 
       recipe will be adjusted according to the weather.</p>
    <hr />
    <form>
        <input type="hidden" asp-for="@Model.BreadId" value="@Model.BreadId" />

        <input asp-for="City" />
        <input type="submit" asp-action="City" class="btn btn-primary" value="Submit Your City" />
    </form>
</div>

BreadBuilder/Views/Weather/ViewWeather.cshtml
@model BreadBuilder.ViewModels.WeatherViewModel

@{
    ViewData["Title"] = "ViewWeather";
}

<h2>Weather</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Temp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Temp) F
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Humidity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Humidity) %
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DewPoint)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DewPoint)
        </dd>
    </dl>
</div>




<h2>@Model.Bread.Name</h2>
<hr />
<br />
<h5>Hydration: @Model.Hydration %</h5>
<hr />
<div class="container-fluid bg-warning">
    <p>@Model.AdjustmentPercent @Model.AdjustmentMessage</p>
</div>

<h3>Convert Your Recipe</h3>
<div>
    @Html.ActionLink("Grams", "ConvertToGrams", "Bread", new { id = Model.Bread.ID }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Ounces", "ConvertToOunces", "Bread", new { id = Model.Bread.ID }, new { @class = "btn btn-primary" })
</div>
<h3><b>Ingredients</b></h3>
<hr />
<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <th>Value</th>
        <th>Unit</th>
    </tr>
    @foreach (var item in Model.Items)
    {

        <tr>


            <td>@item.RecipeIngredient.Name</td>

            <td>@item.RecipeMeasurement.Value</td>

            <td>@item.RecipeMeasurement.Unit</td>


        </tr>

    }

</table>
<hr />

<h5>Totals:</h5>
<div>
    <ul>
        @Model.TotalWeights[0] Oz
    </ul>
    <ul>
        @Model.TotalWeights[1] G
    </ul>
</div>



<hr />
<h3><b>Bake Time</b></h3>
<p>@Model.Bread.BakeTime minutes</p>
<hr />
<h3><b>Bake Temp</b></h3>
<p>@Model.Bread.BakeTemp F</p>
<hr />
<div>
    <h3><b>Fermentation Time</b></h3>
    <p>@Model.Bread.FermentTime minutes</p>
</div>
<hr />
<div>
    <h3><b>ProofTime</b></h3>
    <p>@Model.Bread.ProofTime minutes</p>
</div>
<hr />
<h3><b>Instructions</b></h3>
<p>@Model.Bread.Instructions</p>
<br />
<br />
<br />
<br />
<div>
    <a asp-controller="User" asp-action="UserRecipeList" class="btn btn-primary">Back to List</a>
</div>
<br />
<br />
<div>

    @Html.ActionLink("New City", "Index", new { id = Model.BreadID }, new { @class = "btn btn-primary" })
</div>