BreadBuilder/Models/Ingredient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BreadBuilder.Models
{
    public class Ingredient
    {
        public int ID { get; set; }
        public string Name { get; set; }

       

      
    }
}

BreadBuilder/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BreadBuilder.Data;
using BreadBuilder.Models;
using BreadBuilder.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BreadBuilder.Controllers
{
    public class IngredientController : Controller
    {
        private BreadDbContext context;

        public IngredientController(BreadDbContext dbContext)
        {
            context = dbContext;
        }


        public IActionResult Index()
        {

            IList<Ingredient> ingredients = context.Ingredients.ToList();
            IList<Measurement> measurements = context.Measurements.ToList();
            IList<RecipeItem> recipeItems = context.RecipeItems.ToList();

            RemoveIngredientViewModel removeIngredientViewModel = new RemoveIngredientViewModel
            {
                Ingredients = ingredients,
                Measurements = measurements,
                RecipeItems = recipeItems
            };
            return View(removeIngredientViewModel);
        }

        public IActionResult DeleteMeasurement(int id)
        {
            Measurement theMeasurement = context.Measurements.Single(m => m.ID == id);
            context.Measurements.Remove(theMeasurement);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteIngredient(int id)
        {
            Ingredient theIngredient = context.Ingredients.Single(i => i.ID == id);
            context.Ingredients.Remove(theIngredient);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteRecipeItem(int id)
        {
            RecipeItem theRecipeItem = context.RecipeItems.Single(r => r.ID == id);
            context.RecipeItems.Remove(theRecipeItem);
            context.SaveChanges();

            return RedirectToAction("Index");
        }


        /*
         * Section For adding individual ingredients...  Needs to be deleted if not used...
        public IActionResult Add()
        {
            AddIngredientViewModel addIngredientViewModel = new AddIngredientViewModel();

            //creates a list from the Ingredient Data page
            List<Ingredient> ingredientList = context.Ingredients.ToList();

            //loops through that list and adds the items to the ingredient list in the ViewModel
            foreach (var item in ingredientList)
            {
                addIngredientViewModel.ingredients.Add(item);
            }


            return View(addIngredientViewModel);
        }
        
        

        [HttpPost]
        public IActionResult Add(AddIngredientViewModel addIngredientViewModel)
        {
            if (ModelState.IsValid)
            {
                Ingredient newIngredient = new Ingredient
                {
                    Name = addIngredientViewModel.Name

                };

                context.Ingredients.Add(newIngredient);
                context.SaveChanges();

                //creates a list from the Ingredient Data page
                List<Ingredient> ingredientList = context.Ingredients.ToList();

                //loops through that list and adds the items to the ingredient list in the ViewModel
                foreach(var item in ingredientList)
                {
                    addIngredientViewModel.ingredients.Add(item);
                }

                

                return Redirect("/Ingredient");



            }

            return View(addIngredientViewModel);

        }
        */
    }
}

BreadBuilder/Views/Ingredient/Add.cshtml
@model BreadBuilder.ViewModels.AddIngredientViewModel;

@{
    ViewData["Title"] = "Add";
}



<h2>Add Some Ingredients</h2>
<hr />

@if (Model.ingredients.Count == 0)
{
    <p>no ingredients saved</p>

}

@foreach(var item in Model.ingredients)
{
    <li>
        <ul>@item.Name</ul>
    </li>

}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BreadBuilder/Views/Ingredient/Index.cshtml
@model BreadBuilder.ViewModels.RemoveIngredientViewModel
@{
    ViewData["Title"] = "Ingredients";
}

<h2>Ingredients</h2>
<br />

@foreach(var item in Model.Ingredients)
{
    <li>
        <ul>
            @item.Name
            @Html.ActionLink("Delete", "DeleteIngredient", new { id = item.ID })
        </ul>
    </li>
}

<br />

<h2>Measurements</h2>
@foreach(var item in Model.Measurements)
{ 
    <li>
        <ul>
            @item.Value
            @Html.ActionLink("Delete", "DeleteMeasurement", new { id = item.ID })
        </ul>
    </li>
}

<br />

<h2>RecipeItems</h2>
@foreach(var item in Model.RecipeItems)
{ 
    <li>
        <ul>
            @item.RecipeIngredient.Name
            @item.RecipeMeasurement.Value
            @Html.ActionLink("Delete", "DeleteRecipeItem", new { id = item.ID })
        </ul>
    </li>
}

<a asp-controller="Ingredient" asp-action="Index">Index</a>